name: getworld
description:  A dart package to get countries information.
version: 1.0.0
homepage: https://github.com/AmremadDev/GetWorld_Projects/tree/master/country_list_picker/getworld

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
