name: getworld
description:  A dart package to get countries, languages and currencies data.
version: 1.0.1
homepage: https://github.com/AmremadDev/getworld

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
dependencies:
  collection: ^1.17.0
  intl: ^0.17.0
  vm_service: ^9.4.0

